In [1]:
from pyspark.sql import SparkSession

# Membuat Spark session
spark = SparkSession.builder.appName("BigData").getOrCreate()

# Data sederhana
data = [("Yanto", 20), ("Budi", 30)]

# Membuat DataFrame
df = spark.createDataFrame(data, ["nama", "usia"])

# Menampilkan isi DataFrame
df.show()

+-----+----+
| nama|usia|
+-----+----+
|Yanto|  20|
| Budi|  30|
+-----+----+